
services:
  broker:
    build: .
    command: node broker.js
    ports:
      - "5559:5559"
      - "5560:5560"

  server:
    build: .
    command: node servidor.js
    depends_on:
      - broker

  client:
    build: .
    command: node client.js
    depends_on:
      - broker